<%def name="show_menu(type_op)">
    % if type_op!="":
        <a href="${make_url('admin/pastafari/servers?group_id='+str(group_id))}">
    % endif
        ${lang('pastafari', 'all_servers', 'All servers')}
    % if type_op!="":
        </a>
    % endif
    - 
    % if type_op!="down":
        <a href="${make_url('admin/pastafari/servers?type=down&group_id='+str(group_id))}">
    % endif
        ${lang('pastafari', 'servers_down', 'Servers down')}
    % if type_op!="down":
        </a>
    % endif
    - 
    % if type_op!="heavy":
        <a href="${make_url('admin/pastafari/servers?type=heavy&group_id='+str(group_id))}">
    % endif
        ${lang('pastafari', 'servers_heavy_loaded', 'Servers heavily loaded')}
    % if type_op!="heavy":
    </a>
    % endif
    - 
    % if type_op!="disks":
        <a href="${make_url('admin/pastafari/servers?type=disks&group_id='+str(group_id))}">
    % endif
        ${lang('pastafari', 'servers_bloated_disks', 'Servers with bloated disks')}
    % if type_op!="disks":
        </a>
    % endif
    - 
    % if type_op!="update_servers":
        <a href="${make_url('admin/pastafari/servers?type=update_servers&group_id='+str(group_id))}">
    % endif
        ${lang('pastafari', 'servers_to_update', 'Servers to update')}
    % if type_op!="update_servers":
        </a>
    % endif
    -
    % if type_op!="task_servers":
        <a href="${make_url('admin/pastafari/servers?type=task_servers&group_id='+str(group_id))}">
    % endif
        ${lang('pastafari', 'make_task_selected_servers', 'Make task in selected servers')}
    % if type_op!="task_servers":
        </a>
    % endif
</%def>
<form method="get" action="${make_admin_url('pastafari/servers')}" id="change_group">
<p>${select_form_group.form()|n}</p>
<input type="hidden" name="type" value="${type_op}" />
</form>
<p><a href="${make_url('admin/pastafari/servers?op=1&group_id='+str(group_id))}">${lang('pastafari', 'add_existent_server', 'Add existing server')}</a></p>
<p>
${show_menu(type_op)}
</p>
% if yes_form==1 or yes_yorm==2:
<form method="post" name="update_servers" id="update_servers" action="${make_url('pastafari/updateservers')}">
% endif
${show_servers|n}
% if yes_form==1 or yes_yorm==2:
${csrf_token()|n}
% endif
% if yes_form==1:
<input type="submit" value="${lang('pastafari', 'update_selected_servers', 'Update selected servers')}" /> <input type="button" onclick="location.href='${make_url('pastafari/updateservers')}';" value="${lang('pastafari', 'update_all_servers', 'Update all servers')}" />
</form>
% elif yes_form==2:
<input type="submit" value="${lang('pastafari', 'make_task_selected_servers', 'Make task in selected servers')}" /> <input type="button" onclick="location.href='${make_url('pastafari/maketask')}';" value="${lang('pastafari', 'make_task_in_all', 'Make task in all servers')}" />
</form>
% endif
% if yes_form==1 or yes_yorm==2:
<script>

$('#update_servers').submit( function () {

    if(!$("input:checkbox:checked").length > 0)
    {
        
        alert('No servers selected');
        
        return false;
        
    }

});
</script>
% endif
<script>
$('#change_group_id_form').change( function () {
       
       $('#change_group').submit();
        
    });
</script>
