<div class="dashboard_cont">
    <h3 class="title_cont">
        Total hosts
    </h3>
    <div class="content_cont">
        <span id="total_servers"></span>
    </div>
</div>
<div class="dashboard_cont">
    <h3 class="title_cont">
        Hosts down
    </h3>
    <div class="content_cont">
       <div id="all_hosts_running" style="display:none;">
        All hosts running and ok!!!
        </div>
        <div id="error_hosts_running" style="display:none;">
            <p><span class="error"><span id="hosts_down"></span> HOSTS DOWN, HOSTS DOWN</span></p>
            <p><a target="_blank" href="${make_url('admin/pastafari/servers', {'type': 'down'})}">View Servers down</a></p>
        </div>
    </div>
</div>
<div class="dashboard_cont">
     <h3 class="title_cont">
        Servers that need updates
    </h3>
    <div class="content_cont">
        <div id="servers_need_updates" style="display:none;">
            Servers need updates
            <p><a target="_blank" href="${make_url('admin/pastafari/servers', {'type': 'update_servers'})}">Update servers</a></p>
        </div>
        <div id="no_servers_need_updates" style="display:none;">
            No servers need updates
        </div>
    </div>
</div>
<div class="dashboard_cont">
    <h3 class="title_cont">
        Disks
    </h3>
    <div class="content_cont">
        <div class="pie">
            <canvas id="canvas_disk"></canvas>
        </div>
        <div id="servers_bloated_disks" style="display:none;">
        <a target="_blank" href="${make_url('admin/pastafari/servers', {'type': 'disks'})}">Hosts with heavy use of disks</a>
        </div>
    </div>
</div>
<div class="dashboard_cont">
    <h3 class="title_cont">
        Network use
    </h3>
    <div class="content_cont">
        <div class="pie">
            <canvas id="canvas_net"></canvas>
        </div>
        <!--View servers with heavy use of network-->
    </div>
</div>
<div class="dashboard_cont">
    <h3 class="title_cont">
        Hosts load
    </h3>
    <div class="content_cont">
        <div class="pie">
            <canvas id="canvas"></canvas>
        </div>
       <div id="heavy_servers" style="display:none;">
            <p><a href="${make_url('admin/pastafari/servers', {'type': 'heavy'})}">View heavily loaded servers</a></p>
        </div>
    </div>
</div>
<script>
    
    var ctx_cpu = document.getElementById("canvas").getContext("2d");
    
    var data_cpu = {
        labels: [
            "0% - 30%",
            "30% - 70%",
            "70% - 100%"
        ],
        datasets: [
            {
                data: [0, 0, 0],
                backgroundColor: [
                    "#FF6384",
                    "#8f1100",
                    "#FF0000"
                ]
            }]
    };
    
    options_cpu={
        title: {
            display: true,
            text: 'Global load of servers'
        },
        responsive: true,
        legend: {
                position: 'bottom',
        }
    };
    
    var cpu_pie = new Chart(ctx_cpu,{
        type: 'pie',
        data: data_cpu,
        options: options_cpu
    });
    
    //Disks
    
    var ctx_disk = document.getElementById("canvas_disk").getContext("2d");
    
    var data_disk = {
        labels: [
            "Used",
            "Free"
        ],
        datasets: [
            {
                data: [0, 0],
                backgroundColor: [
                    "#FF0000",
                    "#0000FF"
                ]
            }]
    };
    
    options={
        title: {
            display: true,
            text: 'Global use of disks in gygabytes'
        },
        responsive: true,
        legend: {
                position: 'bottom',
        }
    };
    
    var disk_pie = new Chart(ctx_disk,{
        type: 'pie',
        data: data_disk,
        options: options
    });
    
    //Charts for networking
    
    var ctx_net = document.getElementById("canvas_net").getContext("2d");
    
    var data_net = {
        labels: [
            "Out",
            "In"
        ],
        datasets: [
            {
                data: [0, 0],
                backgroundColor: [
                    "#0000FF",
                    "#FF0000"
                ]
            }]
    };
    
    options_net={
        title: {
            display: true,
            text: 'Bytes transfered by network from last boot of servers in megabytes'
        },
        responsive: true,
        legend: {
                position: 'bottom',
        }
    };
    
    var net_pie = new Chart(ctx_net,{
        type: 'pie',
        data: data_net,
        options: options_net
    });
    
    function get_servers() {
    
     $.ajax({
        url: "${make_url('pastafari/getinfo')}",
        method: "GET",
        dataType: "json",
        data: {}
        }).done(function(data) {
            
            //alert(JSON.stringify(data));
            
            $('#total_servers').html(data.num_servers)
            
            if(data.num_servers_down>0)
            {
                $('#error_hosts_running').fadeIn(1000);
                $('#all_hosts_running').fadeOut(1000);
                
                $('#hosts_down').html(data.num_servers_down);
                
                
            }
            else
            {
                
                $('#error_hosts_running').fadeOut(1000);
                $('#all_hosts_running').fadeIn(1000);
                
            }
            
            if(data.num_servers_updates>0)
            {
                $('#servers_need_updates').fadeIn(1000);
                $('#no_servers_need_updates').fadeOut(1000);
                
                
            }
            else
            {
                
                $('#servers_need_updates').fadeOut(1000);
                $('#no_servers_need_updates').fadeIn(1000);
                
            }
        
            //alert(JSON.stringify(disk_pie.data.datasets[0].data));
            
            disk_pie.data.datasets[0].data[0]=((((data.disk_info.total_used)/1024)/1024)/1024).toFixed(2);
            disk_pie.data.datasets[0].data[1]=((((data.disk_info.total_free)/1024)/1024)/1024).toFixed(2);
            
            disk_pie.update();
            
            if(data.num_servers_bloated>0)
            {
                
                $('#servers_bloated_disks').fadeIn(1000);
                
            }
            else
            {
                
                $('#servers_bloated_disks').fadeOut(1000);
                
            }
            
            net_pie.data.datasets[0].data[0]=((((data.net_info.total_bytes_recv)/1024)/1024)).toFixed(2);
            net_pie.data.datasets[0].data[1]=((((data.net_info.total_bytes_sent)/1024)/1024)).toFixed(2);
            
            net_pie.update();
            
            cpu_pie.data.datasets[0].data[0]=data.cpu_info['0-30']
            cpu_pie.data.datasets[0].data[1]=data.cpu_info['30-70']
            cpu_pie.data.datasets[0].data[2]=data.cpu_info['70-100']
            
            cpu_pie.update();
            
            if(data.cpu_info['70-100']>0)
            {
                
                $('#heavy_servers').fadeIn(1000);
                
            }
            else
            {
                
                $('#heavy_servers').fadeOut(1000);
                
            }
            
        
        }).fail(function (data) {
            
            alert(JSON.stringify(data));
            
        });
     
    }
    
    get_servers();
    
    setInterval(get_servers, 120000);

</script>
${add_js_home_local('jquery.min.js', 'admin')}
${add_js_home_local('Chart.min.js', 'pastafari')}
