<h2>${title_task}</h2>
<p>${lang('pastafari', 'num_servers', 'Number of servers')}: <span id="num_servers">${num_servers}</span></p>
<p>${lang('pastafari', 'completed_tasks', 'Completed tasks')}: <span id="num_completed">0</span></p>
<p id="detecting_servers">Detecting servers in progress... <i class="fa fa-cog fa-spin fa-fw"></i></p>
<table class="table_servers">
    <tr class="row_server" id="father_server" style="display:none;">
        <td class="hostname">Hostname</td>
        <td class="progress">In progress <i class="fa fa-cog fa-spin fa-fw"></i> <a href="#" class="server_log" target="_blank">${lang('pastafari', 'server_log', 'Server log')}</a></td>
    </tr>
</table>
<div id="finished" style="display:none;">
    <p><strong>All tasks were finished.</strong></p>
</div>
<script>
    
    total_servers=${num_servers};
    total_servers_done=0;
    
    arr_servers=[]
    
    if(total_servers>0)
    {
        get_servers();
    }
    else
    {
        $('#detecting_servers').html('Sorry, no servers to update');
    }
    
    function get_servers() {
    
     $.ajax({
        url: "${make_url('pastafari/getservers')}/${task_id}",
        method: "GET",
        dataType: "json",
        data: {}
        }).done(function(data) {
            
            c=data.length;
            
            if(c>0)
            {
            
                for(x=0;x<c;x++) {
                    
                    row=$('#father_server').clone().appendTo('.table_servers');
                    
                    row.attr('id', data[x].ip)
                    
                    row.css('display', 'block');
                    
                    row.children('.hostname').html(data[x].hostname);
                    
                    row.children('.progress').children('a').attr('href', '${make_url("pastafari/showprogress")}/${task_id}/'+data[x].ip);
                    
                    
                    arr_servers.push(data[x].ip);
                    
                }
                
                $('#detecting_servers').fadeOut(1);
                
                get_progress_servers();
            }
            else
            {
                
                get_servers();
                
            }
        
        }).fail(function (data) {
            
                alert(JSON.stringify(data));
            
        });
     
    }
        
    function get_progress_servers() {
        
        $.ajax({
        url: "${make_url('pastafari/getprogress')}/${task_id}",
        method: "POST",
        dataType: "json",
        data: {servers: JSON.stringify(arr_servers)}
        }).done(function(data) {
           
           for(x in data) {
               
                if(data[x].status==1) {
                
                    server_index=arr_servers.indexOf(data[x].server)
                    
                    server_dom=$(document.getElementById(data[x].server));
                    
                    if(server_index>-1) {
                    
                        arr_servers.splice(server_index, 1);
                        
                    }
                
                    if(data[x].error==1) {
                        //alert($('#'+data[x].server).attr('id'));
                        //$('#'+data[x].server);
                        
                        server_dom.children('.progress').children('i').removeClass('fa-cog fa-spin fa-fw');
                        server_dom.children('.progress').children('i').addClass('fa-ban');
                        server_dom.children('.progress').children('i').css('color', '#ff0000');
                        server_dom.children('.progress').append(' Error: please, review the log')
                        
                        //alert('#'+data[x].server);
                        
                    }
                    else {
                        
                        server_dom.children('.progress').children('i').removeClass('fa-cog fa-spin fa-fw');
                        server_dom.children('.progress').children('i').addClass('fa-check');
                        server_dom.children('.progress').children('i').css('color', '#005a00');
                        
                        setTimeout(function () {
                            
                            server_dom.fadeOut(1000, function() {
                                
                                this.remove();
                                
                            });
                            
                        }, 5000);
                        
                    }
                    
                    total_servers_done+=1;
                    
                    $('#num_completed').html(total_servers_done);
                }
               
           }
           
            if(total_servers_done<total_servers) {
           
                setTimeout(get_progress_servers, 1000);
        
            }
            else {
                
                $('#finished').fadeIn(1000);
                
            }
        
        }).fail(function (data) {
            
                alert(JSON.stringify(data));
            
        });
        
    }
    
    
    
    
</script>

